services:
  postgres:
    image: postgres:15-bullseye
    restart: always
    environment:
      POSTGRES_DB:        pynance
      POSTGRES_USER:      postgres
      POSTGRES_PASSWORD:  root  
    volumes:
      # - ./pg/data:/var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data
      - ./pg/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL:    root@pg.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - postgres
    ports:
      - "5433:80"

  core:
    build: ./core/
    depends_on: 
      - postgres

volumes:
  - postgres_data